package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizDeviceUsage;
import com.elextec.persist.model.mybatis.BizDeviceUsageExample;
import com.elextec.persist.model.mybatis.BizDeviceUsageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizDeviceUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int countByExample(BizDeviceUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int deleteByExample(BizDeviceUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BizDeviceUsageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int insert(BizDeviceUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int insertSelective(BizDeviceUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    List<BizDeviceUsage> selectByExample(BizDeviceUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    BizDeviceUsage selectByPrimaryKey(BizDeviceUsageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizDeviceUsage record, @Param("example") BizDeviceUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizDeviceUsage record, @Param("example") BizDeviceUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizDeviceUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizDeviceUsage record);
}