package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizDeviceTrack;
import com.elextec.persist.model.mybatis.BizDeviceTrackExample;
import com.elextec.persist.model.mybatis.BizDeviceTrackKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizDeviceTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int countByExample(BizDeviceTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int deleteByExample(BizDeviceTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BizDeviceTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int insert(BizDeviceTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int insertSelective(BizDeviceTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    List<BizDeviceTrack> selectByExample(BizDeviceTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    BizDeviceTrack selectByPrimaryKey(BizDeviceTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizDeviceTrack record, @Param("example") BizDeviceTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizDeviceTrack record, @Param("example") BizDeviceTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizDeviceTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizDeviceTrack record);
}