package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizManufacturer;
import com.elextec.persist.model.mybatis.BizManufacturerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int countByExample(BizManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int deleteByExample(BizManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int insert(BizManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int insertSelective(BizManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    List<BizManufacturer> selectByExample(BizManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    BizManufacturer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizManufacturer record, @Param("example") BizManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizManufacturer record, @Param("example") BizManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizManufacturer record);
}