package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizParts;
import com.elextec.persist.model.mybatis.BizPartsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizPartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int countByExample(BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int deleteByExample(BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int insert(BizParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int insertSelective(BizParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    List<BizParts> selectByExampleWithBLOBs(BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    List<BizParts> selectByExample(BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    BizParts selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizParts record, @Param("example") BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BizParts record, @Param("example") BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizParts record, @Param("example") BizPartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BizParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizParts record);
}