package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizRefVehicleBattery;
import com.elextec.persist.model.mybatis.BizRefVehicleBatteryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizRefVehicleBatteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int countByExample(BizRefVehicleBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int deleteByExample(BizRefVehicleBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int insert(BizRefVehicleBattery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int insertSelective(BizRefVehicleBattery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    List<BizRefVehicleBattery> selectByExample(BizRefVehicleBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    BizRefVehicleBattery selectByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizRefVehicleBattery record, @Param("example") BizRefVehicleBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizRefVehicleBattery record, @Param("example") BizRefVehicleBatteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRefVehicleBattery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRefVehicleBattery record);
}