package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizRefOrgVehicle;
import com.elextec.persist.model.mybatis.BizRefOrgVehicleExample;
import com.elextec.persist.model.mybatis.BizRefOrgVehicleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizRefOrgVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int countByExample(BizRefOrgVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(BizRefOrgVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BizRefOrgVehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int insert(BizRefOrgVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(BizRefOrgVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    List<BizRefOrgVehicle> selectByExample(BizRefOrgVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    BizRefOrgVehicle selectByPrimaryKey(BizRefOrgVehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizRefOrgVehicle record, @Param("example") BizRefOrgVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizRefOrgVehicle record, @Param("example") BizRefOrgVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRefOrgVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRefOrgVehicle record);
}