package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizRefVehicleParts;
import com.elextec.persist.model.mybatis.BizRefVehiclePartsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizRefVehiclePartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int countByExample(BizRefVehiclePartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int deleteByExample(BizRefVehiclePartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int insert(BizRefVehicleParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int insertSelective(BizRefVehicleParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    List<BizRefVehicleParts> selectByExample(BizRefVehiclePartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    BizRefVehicleParts selectByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizRefVehicleParts record, @Param("example") BizRefVehiclePartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizRefVehicleParts record, @Param("example") BizRefVehiclePartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRefVehicleParts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRefVehicleParts record);
}