package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizRefUserVehicle;
import com.elextec.persist.model.mybatis.BizRefUserVehicleExample;
import com.elextec.persist.model.mybatis.BizRefUserVehicleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizRefUserVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int countByExample(BizRefUserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(BizRefUserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BizRefUserVehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int insert(BizRefUserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(BizRefUserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    List<BizRefUserVehicle> selectByExample(BizRefUserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    BizRefUserVehicle selectByPrimaryKey(BizRefUserVehicleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizRefUserVehicle record, @Param("example") BizRefUserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizRefUserVehicle record, @Param("example") BizRefUserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizRefUserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizRefUserVehicle record);
}