package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizVehicle;
import com.elextec.persist.model.mybatis.BizVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int countByExample(BizVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(BizVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int insert(BizVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(BizVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    List<BizVehicle> selectByExample(BizVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    BizVehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizVehicle record, @Param("example") BizVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizVehicle record, @Param("example") BizVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizVehicle record);
}