package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.BizVehicleTrack;
import com.elextec.persist.model.mybatis.BizVehicleTrackExample;
import com.elextec.persist.model.mybatis.BizVehicleTrackKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizVehicleTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int countByExample(BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int deleteByExample(BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BizVehicleTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int insert(BizVehicleTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int insertSelective(BizVehicleTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    List<BizVehicleTrack> selectByExampleWithBLOBs(BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    List<BizVehicleTrack> selectByExample(BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    BizVehicleTrack selectByPrimaryKey(BizVehicleTrackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizVehicleTrack record, @Param("example") BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") BizVehicleTrack record, @Param("example") BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizVehicleTrack record, @Param("example") BizVehicleTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizVehicleTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BizVehicleTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizVehicleTrack record);
}