package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.SysApply;
import com.elextec.persist.model.mybatis.SysApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int countByExample(SysApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int deleteByExample(SysApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int insert(SysApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int insertSelective(SysApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    List<SysApply> selectByExample(SysApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    SysApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysApply record, @Param("example") SysApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysApply record, @Param("example") SysApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysApply record);
}