package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.SysRefRoleResourcesExample;
import com.elextec.persist.model.mybatis.SysRefRoleResourcesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRefRoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int countByExample(SysRefRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int deleteByExample(SysRefRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysRefRoleResourcesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int insert(SysRefRoleResourcesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int insertSelective(SysRefRoleResourcesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    List<SysRefRoleResourcesKey> selectByExample(SysRefRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRefRoleResourcesKey record, @Param("example") SysRefRoleResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRefRoleResourcesKey record, @Param("example") SysRefRoleResourcesExample example);
}