spring:
  profiles:
    active: dev
  mvc:
    media-types.*: text/html;application/json
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: src/main/resources/static/**,src/main/resources/templates/**
logging:
  config: classpath:logback.xml
localsetting:
  cors:
    flag: true
  upload-root: /root/tomcat-8990/webapps/leaseupload
  download-prefix: http://106.14.172.38:8990/leaseupload
  platform-type: mobile
  login-overtime-sec: 300
  sms:
    url: http://112.74.76.186:8030/service/httpService/httpInterface.do
    username: JSM41961
    password: 5tjfzvne
    verycode: upxg5dedtrk2
    tempid1: JSM41961-0001