spring:
  profiles:
    active: dev
  mvc:
    media-types.*: text/html;application/json
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: src/main/resources/static/**,src/main/resources/templates/**
logging:
  config: classpath:logback.xml
localsetting:
  platform-type: mobile
  login-overtime-sec: 300
  nofilters: /manager/auth/,/mobile/v1/auth/login,/mobile/v1/auth/logout,/mobile/v1/auth/sendsms,/mobile/v1/auth/resetpassword,
  white-flag: false
  white-url:
  black-flag: true
  black-url:
  cors:
    flag: true
  sms:
    url: http://112.74.76.186:8030/service/httpService/httpInterface.do
    username: JSM41961
    password: 5tjfzvne
    verycode: upxg5dedtrk2
    tempid1: JSM41961-0001
  track-stay-time: 900000
  loc-effective-distance: 400
