package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.RecordStatus;
import java.io.Serializable;
import java.util.Date;

public class BizBattery implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_battery
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -7501370955443698409L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_code
     *
     * @mbggenerated
     */
    private String batteryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_name
     *
     * @mbggenerated
     */
    private String batteryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_brand
     *
     * @mbggenerated
     */
    private String batteryBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_pn
     *
     * @mbggenerated
     */
    private String batteryPn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.mfrs_id
     *
     * @mbggenerated
     */
    private String mfrsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_status
     *
     * @mbggenerated
     */
    private RecordStatus batteryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_battery.battery_parameters
     *
     * @mbggenerated
     */
    private String batteryParameters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.id
     *
     * @return the value of biz_battery.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.id
     *
     * @param id the value for biz_battery.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_code
     *
     * @return the value of biz_battery.battery_code
     *
     * @mbggenerated
     */
    public String getBatteryCode() {
        return batteryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_code
     *
     * @param batteryCode the value for biz_battery.battery_code
     *
     * @mbggenerated
     */
    public void setBatteryCode(String batteryCode) {
        this.batteryCode = batteryCode == null ? null : batteryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_name
     *
     * @return the value of biz_battery.battery_name
     *
     * @mbggenerated
     */
    public String getBatteryName() {
        return batteryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_name
     *
     * @param batteryName the value for biz_battery.battery_name
     *
     * @mbggenerated
     */
    public void setBatteryName(String batteryName) {
        this.batteryName = batteryName == null ? null : batteryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_brand
     *
     * @return the value of biz_battery.battery_brand
     *
     * @mbggenerated
     */
    public String getBatteryBrand() {
        return batteryBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_brand
     *
     * @param batteryBrand the value for biz_battery.battery_brand
     *
     * @mbggenerated
     */
    public void setBatteryBrand(String batteryBrand) {
        this.batteryBrand = batteryBrand == null ? null : batteryBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_pn
     *
     * @return the value of biz_battery.battery_pn
     *
     * @mbggenerated
     */
    public String getBatteryPn() {
        return batteryPn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_pn
     *
     * @param batteryPn the value for biz_battery.battery_pn
     *
     * @mbggenerated
     */
    public void setBatteryPn(String batteryPn) {
        this.batteryPn = batteryPn == null ? null : batteryPn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.mfrs_id
     *
     * @return the value of biz_battery.mfrs_id
     *
     * @mbggenerated
     */
    public String getMfrsId() {
        return mfrsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.mfrs_id
     *
     * @param mfrsId the value for biz_battery.mfrs_id
     *
     * @mbggenerated
     */
    public void setMfrsId(String mfrsId) {
        this.mfrsId = mfrsId == null ? null : mfrsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_status
     *
     * @return the value of biz_battery.battery_status
     *
     * @mbggenerated
     */
    public RecordStatus getBatteryStatus() {
        return batteryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_status
     *
     * @param batteryStatus the value for biz_battery.battery_status
     *
     * @mbggenerated
     */
    public void setBatteryStatus(RecordStatus batteryStatus) {
        this.batteryStatus = batteryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.create_user
     *
     * @return the value of biz_battery.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.create_user
     *
     * @param createUser the value for biz_battery.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.create_time
     *
     * @return the value of biz_battery.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.create_time
     *
     * @param createTime the value for biz_battery.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.update_user
     *
     * @return the value of biz_battery.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.update_user
     *
     * @param updateUser the value for biz_battery.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.update_time
     *
     * @return the value of biz_battery.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.update_time
     *
     * @param updateTime the value for biz_battery.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_battery.battery_parameters
     *
     * @return the value of biz_battery.battery_parameters
     *
     * @mbggenerated
     */
    public String getBatteryParameters() {
        return batteryParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_battery.battery_parameters
     *
     * @param batteryParameters the value for biz_battery.battery_parameters
     *
     * @mbggenerated
     */
    public void setBatteryParameters(String batteryParameters) {
        this.batteryParameters = batteryParameters == null ? null : batteryParameters.trim();
    }
}