package com.elextec.persist.model.mybatis;

import java.io.Serializable;

public class BizDeviceConf extends BizDeviceConfKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_device_conf
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 8962375703998921552L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_conf.per_set
     *
     * @mbggenerated
     */
    private Integer perSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_conf.reset
     *
     * @mbggenerated
     */
    private Integer reset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_conf.request
     *
     * @mbggenerated
     */
    private Integer request;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_conf.per_set
     *
     * @return the value of biz_device_conf.per_set
     *
     * @mbggenerated
     */
    public Integer getPerSet() {
        return perSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_conf.per_set
     *
     * @param perSet the value for biz_device_conf.per_set
     *
     * @mbggenerated
     */
    public void setPerSet(Integer perSet) {
        this.perSet = perSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_conf.reset
     *
     * @return the value of biz_device_conf.reset
     *
     * @mbggenerated
     */
    public Integer getReset() {
        return reset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_conf.reset
     *
     * @param reset the value for biz_device_conf.reset
     *
     * @mbggenerated
     */
    public void setReset(Integer reset) {
        this.reset = reset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_conf.request
     *
     * @return the value of biz_device_conf.request
     *
     * @mbggenerated
     */
    public Integer getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_conf.request
     *
     * @param request the value for biz_device_conf.request
     *
     * @mbggenerated
     */
    public void setRequest(Integer request) {
        this.request = request;
    }
}