package com.elextec.persist.model.mybatis;

import java.io.Serializable;

public class BizDeviceUsage extends BizDeviceUsageKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_device_usage
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1132485718340024053L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_usage.use_duration
     *
     * @mbggenerated
     */
    private Long useDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_usage.use_distance
     *
     * @mbggenerated
     */
    private Integer useDistance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_usage.use_duration
     *
     * @return the value of biz_device_usage.use_duration
     *
     * @mbggenerated
     */
    public Long getUseDuration() {
        return useDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_usage.use_duration
     *
     * @param useDuration the value for biz_device_usage.use_duration
     *
     * @mbggenerated
     */
    public void setUseDuration(Long useDuration) {
        this.useDuration = useDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_usage.use_distance
     *
     * @return the value of biz_device_usage.use_distance
     *
     * @mbggenerated
     */
    public Integer getUseDistance() {
        return useDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_usage.use_distance
     *
     * @param useDistance the value for biz_device_usage.use_distance
     *
     * @mbggenerated
     */
    public void setUseDistance(Integer useDistance) {
        this.useDistance = useDistance;
    }
}