package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.DeviceType;
import java.io.Serializable;

public class BizDeviceConfKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_device_conf
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -39125040178059025L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_conf.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_conf.device_type
     *
     * @mbggenerated
     */
    private DeviceType deviceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_conf.device_id
     *
     * @return the value of biz_device_conf.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_conf.device_id
     *
     * @param deviceId the value for biz_device_conf.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_conf.device_type
     *
     * @return the value of biz_device_conf.device_type
     *
     * @mbggenerated
     */
    public DeviceType getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_conf.device_type
     *
     * @param deviceType the value for biz_device_conf.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(DeviceType deviceType) {
        this.deviceType = deviceType;
    }
}