package com.elextec.persist.model.mybatis;

import java.io.Serializable;

public class BizDeviceTrackKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_device_track
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -1212875775516900544L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_track.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_device_track.loc_time
     *
     * @mbggenerated
     */
    private Long locTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_track.device_id
     *
     * @return the value of biz_device_track.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_track.device_id
     *
     * @param deviceId the value for biz_device_track.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_device_track.loc_time
     *
     * @return the value of biz_device_track.loc_time
     *
     * @mbggenerated
     */
    public Long getLocTime() {
        return locTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_device_track.loc_time
     *
     * @param locTime the value for biz_device_track.loc_time
     *
     * @mbggenerated
     */
    public void setLocTime(Long locTime) {
        this.locTime = locTime;
    }
}