package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.MfrsType;
import java.io.Serializable;
import java.util.Date;

public class BizManufacturer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -1561234302853307641L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_name
     *
     * @mbggenerated
     */
    private String mfrsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_type
     *
     * @mbggenerated
     */
    private MfrsType mfrsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_introduce
     *
     * @mbggenerated
     */
    private String mfrsIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_address
     *
     * @mbggenerated
     */
    private String mfrsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_contacts
     *
     * @mbggenerated
     */
    private String mfrsContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_phone
     *
     * @mbggenerated
     */
    private String mfrsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.mfrs_status
     *
     * @mbggenerated
     */
    private String mfrsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_manufacturer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.id
     *
     * @return the value of biz_manufacturer.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.id
     *
     * @param id the value for biz_manufacturer.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_name
     *
     * @return the value of biz_manufacturer.mfrs_name
     *
     * @mbggenerated
     */
    public String getMfrsName() {
        return mfrsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_name
     *
     * @param mfrsName the value for biz_manufacturer.mfrs_name
     *
     * @mbggenerated
     */
    public void setMfrsName(String mfrsName) {
        this.mfrsName = mfrsName == null ? null : mfrsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_type
     *
     * @return the value of biz_manufacturer.mfrs_type
     *
     * @mbggenerated
     */
    public MfrsType getMfrsType() {
        return mfrsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_type
     *
     * @param mfrsType the value for biz_manufacturer.mfrs_type
     *
     * @mbggenerated
     */
    public void setMfrsType(MfrsType mfrsType) {
        this.mfrsType = mfrsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_introduce
     *
     * @return the value of biz_manufacturer.mfrs_introduce
     *
     * @mbggenerated
     */
    public String getMfrsIntroduce() {
        return mfrsIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_introduce
     *
     * @param mfrsIntroduce the value for biz_manufacturer.mfrs_introduce
     *
     * @mbggenerated
     */
    public void setMfrsIntroduce(String mfrsIntroduce) {
        this.mfrsIntroduce = mfrsIntroduce == null ? null : mfrsIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_address
     *
     * @return the value of biz_manufacturer.mfrs_address
     *
     * @mbggenerated
     */
    public String getMfrsAddress() {
        return mfrsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_address
     *
     * @param mfrsAddress the value for biz_manufacturer.mfrs_address
     *
     * @mbggenerated
     */
    public void setMfrsAddress(String mfrsAddress) {
        this.mfrsAddress = mfrsAddress == null ? null : mfrsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_contacts
     *
     * @return the value of biz_manufacturer.mfrs_contacts
     *
     * @mbggenerated
     */
    public String getMfrsContacts() {
        return mfrsContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_contacts
     *
     * @param mfrsContacts the value for biz_manufacturer.mfrs_contacts
     *
     * @mbggenerated
     */
    public void setMfrsContacts(String mfrsContacts) {
        this.mfrsContacts = mfrsContacts == null ? null : mfrsContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_phone
     *
     * @return the value of biz_manufacturer.mfrs_phone
     *
     * @mbggenerated
     */
    public String getMfrsPhone() {
        return mfrsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_phone
     *
     * @param mfrsPhone the value for biz_manufacturer.mfrs_phone
     *
     * @mbggenerated
     */
    public void setMfrsPhone(String mfrsPhone) {
        this.mfrsPhone = mfrsPhone == null ? null : mfrsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.mfrs_status
     *
     * @return the value of biz_manufacturer.mfrs_status
     *
     * @mbggenerated
     */
    public String getMfrsStatus() {
        return mfrsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.mfrs_status
     *
     * @param mfrsStatus the value for biz_manufacturer.mfrs_status
     *
     * @mbggenerated
     */
    public void setMfrsStatus(String mfrsStatus) {
        this.mfrsStatus = mfrsStatus == null ? null : mfrsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.create_user
     *
     * @return the value of biz_manufacturer.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.create_user
     *
     * @param createUser the value for biz_manufacturer.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.create_time
     *
     * @return the value of biz_manufacturer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.create_time
     *
     * @param createTime the value for biz_manufacturer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.update_user
     *
     * @return the value of biz_manufacturer.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.update_user
     *
     * @param updateUser the value for biz_manufacturer.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_manufacturer.update_time
     *
     * @return the value of biz_manufacturer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_manufacturer.update_time
     *
     * @param updateTime the value for biz_manufacturer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}