package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.MfrsType;
import com.elextec.persist.field.enums.RecordStatus;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BizManufacturerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected Integer pageBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected Integer pageSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public BizManufacturerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void setPageBegin(Integer pageBegin) {
        this.pageBegin=pageBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public Integer getPageBegin() {
        return pageBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMfrsNameIsNull() {
            addCriterion("mfrs_name is null");
            return (Criteria) this;
        }

        public Criteria andMfrsNameIsNotNull() {
            addCriterion("mfrs_name is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsNameEqualTo(String value) {
            addCriterion("mfrs_name =", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameNotEqualTo(String value) {
            addCriterion("mfrs_name <>", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameGreaterThan(String value) {
            addCriterion("mfrs_name >", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameGreaterThanOrEqualTo(String value) {
            addCriterion("mfrs_name >=", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameLessThan(String value) {
            addCriterion("mfrs_name <", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameLessThanOrEqualTo(String value) {
            addCriterion("mfrs_name <=", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameLike(String value) {
            addCriterion("mfrs_name like", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameNotLike(String value) {
            addCriterion("mfrs_name not like", value, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameIn(List<String> values) {
            addCriterion("mfrs_name in", values, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameNotIn(List<String> values) {
            addCriterion("mfrs_name not in", values, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameBetween(String value1, String value2) {
            addCriterion("mfrs_name between", value1, value2, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsNameNotBetween(String value1, String value2) {
            addCriterion("mfrs_name not between", value1, value2, "mfrsName");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeIsNull() {
            addCriterion("mfrs_type is null");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeIsNotNull() {
            addCriterion("mfrs_type is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeEqualTo(MfrsType value) {
            addCriterion("mfrs_type =", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeNotEqualTo(MfrsType value) {
            addCriterion("mfrs_type <>", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeGreaterThan(MfrsType value) {
            addCriterion("mfrs_type >", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeGreaterThanOrEqualTo(MfrsType value) {
            addCriterion("mfrs_type >=", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeLessThan(MfrsType value) {
            addCriterion("mfrs_type <", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeLessThanOrEqualTo(MfrsType value) {
            addCriterion("mfrs_type <=", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeLike(MfrsType value) {
            addCriterion("mfrs_type like", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeNotLike(MfrsType value) {
            addCriterion("mfrs_type not like", value, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeIn(List<MfrsType> values) {
            addCriterion("mfrs_type in", values, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeNotIn(List<MfrsType> values) {
            addCriterion("mfrs_type not in", values, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeBetween(MfrsType value1, MfrsType value2) {
            addCriterion("mfrs_type between", value1, value2, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsTypeNotBetween(MfrsType value1, MfrsType value2) {
            addCriterion("mfrs_type not between", value1, value2, "mfrsType");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceIsNull() {
            addCriterion("mfrs_introduce is null");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceIsNotNull() {
            addCriterion("mfrs_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceEqualTo(String value) {
            addCriterion("mfrs_introduce =", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceNotEqualTo(String value) {
            addCriterion("mfrs_introduce <>", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceGreaterThan(String value) {
            addCriterion("mfrs_introduce >", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("mfrs_introduce >=", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceLessThan(String value) {
            addCriterion("mfrs_introduce <", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceLessThanOrEqualTo(String value) {
            addCriterion("mfrs_introduce <=", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceLike(String value) {
            addCriterion("mfrs_introduce like", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceNotLike(String value) {
            addCriterion("mfrs_introduce not like", value, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceIn(List<String> values) {
            addCriterion("mfrs_introduce in", values, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceNotIn(List<String> values) {
            addCriterion("mfrs_introduce not in", values, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceBetween(String value1, String value2) {
            addCriterion("mfrs_introduce between", value1, value2, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsIntroduceNotBetween(String value1, String value2) {
            addCriterion("mfrs_introduce not between", value1, value2, "mfrsIntroduce");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressIsNull() {
            addCriterion("mfrs_address is null");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressIsNotNull() {
            addCriterion("mfrs_address is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressEqualTo(String value) {
            addCriterion("mfrs_address =", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressNotEqualTo(String value) {
            addCriterion("mfrs_address <>", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressGreaterThan(String value) {
            addCriterion("mfrs_address >", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressGreaterThanOrEqualTo(String value) {
            addCriterion("mfrs_address >=", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressLessThan(String value) {
            addCriterion("mfrs_address <", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressLessThanOrEqualTo(String value) {
            addCriterion("mfrs_address <=", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressLike(String value) {
            addCriterion("mfrs_address like", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressNotLike(String value) {
            addCriterion("mfrs_address not like", value, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressIn(List<String> values) {
            addCriterion("mfrs_address in", values, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressNotIn(List<String> values) {
            addCriterion("mfrs_address not in", values, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressBetween(String value1, String value2) {
            addCriterion("mfrs_address between", value1, value2, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsAddressNotBetween(String value1, String value2) {
            addCriterion("mfrs_address not between", value1, value2, "mfrsAddress");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsIsNull() {
            addCriterion("mfrs_contacts is null");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsIsNotNull() {
            addCriterion("mfrs_contacts is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsEqualTo(String value) {
            addCriterion("mfrs_contacts =", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsNotEqualTo(String value) {
            addCriterion("mfrs_contacts <>", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsGreaterThan(String value) {
            addCriterion("mfrs_contacts >", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsGreaterThanOrEqualTo(String value) {
            addCriterion("mfrs_contacts >=", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsLessThan(String value) {
            addCriterion("mfrs_contacts <", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsLessThanOrEqualTo(String value) {
            addCriterion("mfrs_contacts <=", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsLike(String value) {
            addCriterion("mfrs_contacts like", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsNotLike(String value) {
            addCriterion("mfrs_contacts not like", value, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsIn(List<String> values) {
            addCriterion("mfrs_contacts in", values, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsNotIn(List<String> values) {
            addCriterion("mfrs_contacts not in", values, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsBetween(String value1, String value2) {
            addCriterion("mfrs_contacts between", value1, value2, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsContactsNotBetween(String value1, String value2) {
            addCriterion("mfrs_contacts not between", value1, value2, "mfrsContacts");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneIsNull() {
            addCriterion("mfrs_phone is null");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneIsNotNull() {
            addCriterion("mfrs_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneEqualTo(String value) {
            addCriterion("mfrs_phone =", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneNotEqualTo(String value) {
            addCriterion("mfrs_phone <>", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneGreaterThan(String value) {
            addCriterion("mfrs_phone >", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mfrs_phone >=", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneLessThan(String value) {
            addCriterion("mfrs_phone <", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneLessThanOrEqualTo(String value) {
            addCriterion("mfrs_phone <=", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneLike(String value) {
            addCriterion("mfrs_phone like", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneNotLike(String value) {
            addCriterion("mfrs_phone not like", value, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneIn(List<String> values) {
            addCriterion("mfrs_phone in", values, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneNotIn(List<String> values) {
            addCriterion("mfrs_phone not in", values, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneBetween(String value1, String value2) {
            addCriterion("mfrs_phone between", value1, value2, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsPhoneNotBetween(String value1, String value2) {
            addCriterion("mfrs_phone not between", value1, value2, "mfrsPhone");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusIsNull() {
            addCriterion("mfrs_status is null");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusIsNotNull() {
            addCriterion("mfrs_status is not null");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusEqualTo(RecordStatus value) {
            addCriterion("mfrs_status =", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusNotEqualTo(RecordStatus value) {
            addCriterion("mfrs_status <>", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusGreaterThan(RecordStatus value) {
            addCriterion("mfrs_status >", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusGreaterThanOrEqualTo(RecordStatus value) {
            addCriterion("mfrs_status >=", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusLessThan(RecordStatus value) {
            addCriterion("mfrs_status <", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusLessThanOrEqualTo(RecordStatus value) {
            addCriterion("mfrs_status <=", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusLike(RecordStatus value) {
            addCriterion("mfrs_status like", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusNotLike(RecordStatus value) {
            addCriterion("mfrs_status not like", value, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusIn(List<RecordStatus> values) {
            addCriterion("mfrs_status in", values, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusNotIn(List<RecordStatus> values) {
            addCriterion("mfrs_status not in", values, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusBetween(RecordStatus value1, RecordStatus value2) {
            addCriterion("mfrs_status between", value1, value2, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andMfrsStatusNotBetween(RecordStatus value1, RecordStatus value2) {
            addCriterion("mfrs_status not between", value1, value2, "mfrsStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_manufacturer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_manufacturer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}