package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.OrgAndUserType;
import com.elextec.persist.field.enums.RecordStatus;
import java.io.Serializable;
import java.util.Date;

public class BizOrganization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_organization
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -1496685575515870103L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_type
     *
     * @mbggenerated
     */
    private OrgAndUserType orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_introduce
     *
     * @mbggenerated
     */
    private String orgIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_address
     *
     * @mbggenerated
     */
    private String orgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_contacts
     *
     * @mbggenerated
     */
    private String orgContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_phone
     *
     * @mbggenerated
     */
    private String orgPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_business_licences
     *
     * @mbggenerated
     */
    private String orgBusinessLicences;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_status
     *
     * @mbggenerated
     */
    private RecordStatus orgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.id
     *
     * @return the value of biz_organization.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.id
     *
     * @param id the value for biz_organization.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_code
     *
     * @return the value of biz_organization.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_code
     *
     * @param orgCode the value for biz_organization.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_name
     *
     * @return the value of biz_organization.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_name
     *
     * @param orgName the value for biz_organization.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_type
     *
     * @return the value of biz_organization.org_type
     *
     * @mbggenerated
     */
    public OrgAndUserType getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_type
     *
     * @param orgType the value for biz_organization.org_type
     *
     * @mbggenerated
     */
    public void setOrgType(OrgAndUserType orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_introduce
     *
     * @return the value of biz_organization.org_introduce
     *
     * @mbggenerated
     */
    public String getOrgIntroduce() {
        return orgIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_introduce
     *
     * @param orgIntroduce the value for biz_organization.org_introduce
     *
     * @mbggenerated
     */
    public void setOrgIntroduce(String orgIntroduce) {
        this.orgIntroduce = orgIntroduce == null ? null : orgIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_address
     *
     * @return the value of biz_organization.org_address
     *
     * @mbggenerated
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_address
     *
     * @param orgAddress the value for biz_organization.org_address
     *
     * @mbggenerated
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_contacts
     *
     * @return the value of biz_organization.org_contacts
     *
     * @mbggenerated
     */
    public String getOrgContacts() {
        return orgContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_contacts
     *
     * @param orgContacts the value for biz_organization.org_contacts
     *
     * @mbggenerated
     */
    public void setOrgContacts(String orgContacts) {
        this.orgContacts = orgContacts == null ? null : orgContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_phone
     *
     * @return the value of biz_organization.org_phone
     *
     * @mbggenerated
     */
    public String getOrgPhone() {
        return orgPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_phone
     *
     * @param orgPhone the value for biz_organization.org_phone
     *
     * @mbggenerated
     */
    public void setOrgPhone(String orgPhone) {
        this.orgPhone = orgPhone == null ? null : orgPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_business_licences
     *
     * @return the value of biz_organization.org_business_licences
     *
     * @mbggenerated
     */
    public String getOrgBusinessLicences() {
        return orgBusinessLicences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_business_licences
     *
     * @param orgBusinessLicences the value for biz_organization.org_business_licences
     *
     * @mbggenerated
     */
    public void setOrgBusinessLicences(String orgBusinessLicences) {
        this.orgBusinessLicences = orgBusinessLicences == null ? null : orgBusinessLicences.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_status
     *
     * @return the value of biz_organization.org_status
     *
     * @mbggenerated
     */
    public RecordStatus getOrgStatus() {
        return orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_status
     *
     * @param orgStatus the value for biz_organization.org_status
     *
     * @mbggenerated
     */
    public void setOrgStatus(RecordStatus orgStatus) {
        this.orgStatus = orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.create_user
     *
     * @return the value of biz_organization.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.create_user
     *
     * @param createUser the value for biz_organization.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.create_time
     *
     * @return the value of biz_organization.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.create_time
     *
     * @param createTime the value for biz_organization.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.update_user
     *
     * @return the value of biz_organization.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.update_user
     *
     * @param updateUser the value for biz_organization.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.update_time
     *
     * @return the value of biz_organization.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.update_time
     *
     * @param updateTime the value for biz_organization.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}