package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class BizRefUserVehicle extends BizRefUserVehicleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 8168874700461662212L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_user_vehicle.bind_time
     *
     * @mbggenerated
     */
    private Date bindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_user_vehicle.unbind_time
     *
     * @mbggenerated
     */
    private Date unbindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_user_vehicle.bind_time
     *
     * @return the value of biz_ref_user_vehicle.bind_time
     *
     * @mbggenerated
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_user_vehicle.bind_time
     *
     * @param bindTime the value for biz_ref_user_vehicle.bind_time
     *
     * @mbggenerated
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_user_vehicle.unbind_time
     *
     * @return the value of biz_ref_user_vehicle.unbind_time
     *
     * @mbggenerated
     */
    public Date getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_user_vehicle.unbind_time
     *
     * @param unbindTime the value for biz_ref_user_vehicle.unbind_time
     *
     * @mbggenerated
     */
    public void setUnbindTime(Date unbindTime) {
        this.unbindTime = unbindTime;
    }
}