package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class BizRefVehicleParts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_vehicle_parts
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -5005295630128894895L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_parts.vehicle_id
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_parts.parts_id
     *
     * @mbggenerated
     */
    private String partsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_parts.bind_time
     *
     * @mbggenerated
     */
    private Date bindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_parts.unbind_time
     *
     * @mbggenerated
     */
    private Date unbindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_parts.vehicle_id
     *
     * @return the value of biz_ref_vehicle_parts.vehicle_id
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_parts.vehicle_id
     *
     * @param vehicleId the value for biz_ref_vehicle_parts.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_parts.parts_id
     *
     * @return the value of biz_ref_vehicle_parts.parts_id
     *
     * @mbggenerated
     */
    public String getPartsId() {
        return partsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_parts.parts_id
     *
     * @param partsId the value for biz_ref_vehicle_parts.parts_id
     *
     * @mbggenerated
     */
    public void setPartsId(String partsId) {
        this.partsId = partsId == null ? null : partsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_parts.bind_time
     *
     * @return the value of biz_ref_vehicle_parts.bind_time
     *
     * @mbggenerated
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_parts.bind_time
     *
     * @param bindTime the value for biz_ref_vehicle_parts.bind_time
     *
     * @mbggenerated
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_parts.unbind_time
     *
     * @return the value of biz_ref_vehicle_parts.unbind_time
     *
     * @mbggenerated
     */
    public Date getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_parts.unbind_time
     *
     * @param unbindTime the value for biz_ref_vehicle_parts.unbind_time
     *
     * @mbggenerated
     */
    public void setUnbindTime(Date unbindTime) {
        this.unbindTime = unbindTime;
    }
}