package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class BizRefOrgVehicle extends BizRefOrgVehicleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -7472378758654144475L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_org_vehicle.unbind_time
     *
     * @mbggenerated
     */
    private Date unbindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_org_vehicle.unbind_time
     *
     * @return the value of biz_ref_org_vehicle.unbind_time
     *
     * @mbggenerated
     */
    public Date getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_org_vehicle.unbind_time
     *
     * @param unbindTime the value for biz_ref_org_vehicle.unbind_time
     *
     * @mbggenerated
     */
    public void setUnbindTime(Date unbindTime) {
        this.unbindTime = unbindTime;
    }
}