package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class BizRefVehicleBattery implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_vehicle_battery
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 4511102671901763390L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_battery.vehicle_id
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_battery.battery_id
     *
     * @mbggenerated
     */
    private String batteryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_battery.bind_time
     *
     * @mbggenerated
     */
    private Date bindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_vehicle_battery.unbind_time
     *
     * @mbggenerated
     */
    private Date unbindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_battery.vehicle_id
     *
     * @return the value of biz_ref_vehicle_battery.vehicle_id
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_battery.vehicle_id
     *
     * @param vehicleId the value for biz_ref_vehicle_battery.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_battery.battery_id
     *
     * @return the value of biz_ref_vehicle_battery.battery_id
     *
     * @mbggenerated
     */
    public String getBatteryId() {
        return batteryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_battery.battery_id
     *
     * @param batteryId the value for biz_ref_vehicle_battery.battery_id
     *
     * @mbggenerated
     */
    public void setBatteryId(String batteryId) {
        this.batteryId = batteryId == null ? null : batteryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_battery.bind_time
     *
     * @return the value of biz_ref_vehicle_battery.bind_time
     *
     * @mbggenerated
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_battery.bind_time
     *
     * @param bindTime the value for biz_ref_vehicle_battery.bind_time
     *
     * @mbggenerated
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_vehicle_battery.unbind_time
     *
     * @return the value of biz_ref_vehicle_battery.unbind_time
     *
     * @mbggenerated
     */
    public Date getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_vehicle_battery.unbind_time
     *
     * @param unbindTime the value for biz_ref_vehicle_battery.unbind_time
     *
     * @mbggenerated
     */
    public void setUnbindTime(Date unbindTime) {
        this.unbindTime = unbindTime;
    }
}