package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class BizRefOrgVehicleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_org_vehicle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 5671882461250922490L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_org_vehicle.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_org_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_org_vehicle.bind_time
     *
     * @mbggenerated
     */
    private Date bindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_org_vehicle.org_id
     *
     * @return the value of biz_ref_org_vehicle.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_org_vehicle.org_id
     *
     * @param orgId the value for biz_ref_org_vehicle.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_org_vehicle.vehicle_id
     *
     * @return the value of biz_ref_org_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_org_vehicle.vehicle_id
     *
     * @param vehicleId the value for biz_ref_org_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_org_vehicle.bind_time
     *
     * @return the value of biz_ref_org_vehicle.bind_time
     *
     * @mbggenerated
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_org_vehicle.bind_time
     *
     * @param bindTime the value for biz_ref_org_vehicle.bind_time
     *
     * @mbggenerated
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }
}