package com.elextec.persist.model.mybatis;

import java.io.Serializable;

public class BizRefUserVehicleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_ref_user_vehicle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -8948362996735436869L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_user_vehicle.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_ref_user_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    private String vehicleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_user_vehicle.user_id
     *
     * @return the value of biz_ref_user_vehicle.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_user_vehicle.user_id
     *
     * @param userId the value for biz_ref_user_vehicle.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_ref_user_vehicle.vehicle_id
     *
     * @return the value of biz_ref_user_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_ref_user_vehicle.vehicle_id
     *
     * @param vehicleId the value for biz_ref_user_vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }
}