package com.elextec.persist.model.mybatis;

import java.io.Serializable;

public class BizVehicleTrack extends BizVehicleTrackKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_vehicle_track
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -1329448442810856267L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle_track.end_time
     *
     * @mbggenerated
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle_track.task_info
     *
     * @mbggenerated
     */
    private String taskInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle_track.locations
     *
     * @mbggenerated
     */
    private String locations;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle_track.end_time
     *
     * @return the value of biz_vehicle_track.end_time
     *
     * @mbggenerated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle_track.end_time
     *
     * @param endTime the value for biz_vehicle_track.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle_track.task_info
     *
     * @return the value of biz_vehicle_track.task_info
     *
     * @mbggenerated
     */
    public String getTaskInfo() {
        return taskInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle_track.task_info
     *
     * @param taskInfo the value for biz_vehicle_track.task_info
     *
     * @mbggenerated
     */
    public void setTaskInfo(String taskInfo) {
        this.taskInfo = taskInfo == null ? null : taskInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle_track.locations
     *
     * @return the value of biz_vehicle_track.locations
     *
     * @mbggenerated
     */
    public String getLocations() {
        return locations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle_track.locations
     *
     * @param locations the value for biz_vehicle_track.locations
     *
     * @mbggenerated
     */
    public void setLocations(String locations) {
        this.locations = locations == null ? null : locations.trim();
    }
}