package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.RecordStatus;
import java.io.Serializable;
import java.util.Date;

public class BizVehicle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_vehicle
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -7501370937590520266L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.vehicle_code
     *
     * @mbggenerated
     */
    private String vehicleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.vehicle_pn
     *
     * @mbggenerated
     */
    private String vehiclePn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.vehicle_brand
     *
     * @mbggenerated
     */
    private String vehicleBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.vehicle_made_in
     *
     * @mbggenerated
     */
    private String vehicleMadeIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.mfrs_id
     *
     * @mbggenerated
     */
    private String mfrsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.vehicle_status
     *
     * @mbggenerated
     */
    private RecordStatus vehicleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_vehicle.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.id
     *
     * @return the value of biz_vehicle.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.id
     *
     * @param id the value for biz_vehicle.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.vehicle_code
     *
     * @return the value of biz_vehicle.vehicle_code
     *
     * @mbggenerated
     */
    public String getVehicleCode() {
        return vehicleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.vehicle_code
     *
     * @param vehicleCode the value for biz_vehicle.vehicle_code
     *
     * @mbggenerated
     */
    public void setVehicleCode(String vehicleCode) {
        this.vehicleCode = vehicleCode == null ? null : vehicleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.vehicle_pn
     *
     * @return the value of biz_vehicle.vehicle_pn
     *
     * @mbggenerated
     */
    public String getVehiclePn() {
        return vehiclePn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.vehicle_pn
     *
     * @param vehiclePn the value for biz_vehicle.vehicle_pn
     *
     * @mbggenerated
     */
    public void setVehiclePn(String vehiclePn) {
        this.vehiclePn = vehiclePn == null ? null : vehiclePn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.vehicle_brand
     *
     * @return the value of biz_vehicle.vehicle_brand
     *
     * @mbggenerated
     */
    public String getVehicleBrand() {
        return vehicleBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.vehicle_brand
     *
     * @param vehicleBrand the value for biz_vehicle.vehicle_brand
     *
     * @mbggenerated
     */
    public void setVehicleBrand(String vehicleBrand) {
        this.vehicleBrand = vehicleBrand == null ? null : vehicleBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.vehicle_made_in
     *
     * @return the value of biz_vehicle.vehicle_made_in
     *
     * @mbggenerated
     */
    public String getVehicleMadeIn() {
        return vehicleMadeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.vehicle_made_in
     *
     * @param vehicleMadeIn the value for biz_vehicle.vehicle_made_in
     *
     * @mbggenerated
     */
    public void setVehicleMadeIn(String vehicleMadeIn) {
        this.vehicleMadeIn = vehicleMadeIn == null ? null : vehicleMadeIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.mfrs_id
     *
     * @return the value of biz_vehicle.mfrs_id
     *
     * @mbggenerated
     */
    public String getMfrsId() {
        return mfrsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.mfrs_id
     *
     * @param mfrsId the value for biz_vehicle.mfrs_id
     *
     * @mbggenerated
     */
    public void setMfrsId(String mfrsId) {
        this.mfrsId = mfrsId == null ? null : mfrsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.vehicle_status
     *
     * @return the value of biz_vehicle.vehicle_status
     *
     * @mbggenerated
     */
    public RecordStatus getVehicleStatus() {
        return vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.vehicle_status
     *
     * @param vehicleStatus the value for biz_vehicle.vehicle_status
     *
     * @mbggenerated
     */
    public void setVehicleStatus(RecordStatus vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.create_user
     *
     * @return the value of biz_vehicle.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.create_user
     *
     * @param createUser the value for biz_vehicle.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.create_time
     *
     * @return the value of biz_vehicle.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.create_time
     *
     * @param createTime the value for biz_vehicle.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.update_user
     *
     * @return the value of biz_vehicle.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.update_user
     *
     * @param updateUser the value for biz_vehicle.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_vehicle.update_time
     *
     * @return the value of biz_vehicle.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_vehicle.update_time
     *
     * @param updateTime the value for biz_vehicle.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}