package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.ApplyTypeAndStatus;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected Integer pageBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected Integer pageSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public SysApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void setPageBegin(Integer pageBegin) {
        this.pageBegin=pageBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public Integer getPageBegin() {
        return pageBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplyTitleIsNull() {
            addCriterion("apply_title is null");
            return (Criteria) this;
        }

        public Criteria andApplyTitleIsNotNull() {
            addCriterion("apply_title is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTitleEqualTo(String value) {
            addCriterion("apply_title =", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleNotEqualTo(String value) {
            addCriterion("apply_title <>", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleGreaterThan(String value) {
            addCriterion("apply_title >", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleGreaterThanOrEqualTo(String value) {
            addCriterion("apply_title >=", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleLessThan(String value) {
            addCriterion("apply_title <", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleLessThanOrEqualTo(String value) {
            addCriterion("apply_title <=", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleLike(String value) {
            addCriterion("apply_title like", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleNotLike(String value) {
            addCriterion("apply_title not like", value, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleIn(List<String> values) {
            addCriterion("apply_title in", values, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleNotIn(List<String> values) {
            addCriterion("apply_title not in", values, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleBetween(String value1, String value2) {
            addCriterion("apply_title between", value1, value2, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyTitleNotBetween(String value1, String value2) {
            addCriterion("apply_title not between", value1, value2, "applyTitle");
            return (Criteria) this;
        }

        public Criteria andApplyContentIsNull() {
            addCriterion("apply_content is null");
            return (Criteria) this;
        }

        public Criteria andApplyContentIsNotNull() {
            addCriterion("apply_content is not null");
            return (Criteria) this;
        }

        public Criteria andApplyContentEqualTo(String value) {
            addCriterion("apply_content =", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentNotEqualTo(String value) {
            addCriterion("apply_content <>", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentGreaterThan(String value) {
            addCriterion("apply_content >", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentGreaterThanOrEqualTo(String value) {
            addCriterion("apply_content >=", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentLessThan(String value) {
            addCriterion("apply_content <", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentLessThanOrEqualTo(String value) {
            addCriterion("apply_content <=", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentLike(String value) {
            addCriterion("apply_content like", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentNotLike(String value) {
            addCriterion("apply_content not like", value, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentIn(List<String> values) {
            addCriterion("apply_content in", values, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentNotIn(List<String> values) {
            addCriterion("apply_content not in", values, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentBetween(String value1, String value2) {
            addCriterion("apply_content between", value1, value2, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyContentNotBetween(String value1, String value2) {
            addCriterion("apply_content not between", value1, value2, "applyContent");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNull() {
            addCriterion("apply_type is null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIsNotNull() {
            addCriterion("apply_type is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTypeEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_type =", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_type <>", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThan(ApplyTypeAndStatus value) {
            addCriterion("apply_type >", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeGreaterThanOrEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_type >=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThan(ApplyTypeAndStatus value) {
            addCriterion("apply_type <", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLessThanOrEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_type <=", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeLike(ApplyTypeAndStatus value) {
            addCriterion("apply_type like", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotLike(ApplyTypeAndStatus value) {
            addCriterion("apply_type not like", value, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeIn(List<ApplyTypeAndStatus> values) {
            addCriterion("apply_type in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotIn(List<ApplyTypeAndStatus> values) {
            addCriterion("apply_type not in", values, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeBetween(ApplyTypeAndStatus value1, ApplyTypeAndStatus value2) {
            addCriterion("apply_type between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyTypeNotBetween(ApplyTypeAndStatus value1, ApplyTypeAndStatus value2) {
            addCriterion("apply_type not between", value1, value2, "applyType");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNull() {
            addCriterion("apply_status is null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNotNull() {
            addCriterion("apply_status is not null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_status =", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_status <>", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThan(ApplyTypeAndStatus value) {
            addCriterion("apply_status >", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThanOrEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_status >=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThan(ApplyTypeAndStatus value) {
            addCriterion("apply_status <", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThanOrEqualTo(ApplyTypeAndStatus value) {
            addCriterion("apply_status <=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLike(ApplyTypeAndStatus value) {
            addCriterion("apply_status like", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotLike(ApplyTypeAndStatus value) {
            addCriterion("apply_status not like", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIn(List<ApplyTypeAndStatus> values) {
            addCriterion("apply_status in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotIn(List<ApplyTypeAndStatus> values) {
            addCriterion("apply_status not in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusBetween(ApplyTypeAndStatus value1, ApplyTypeAndStatus value2) {
            addCriterion("apply_status between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotBetween(ApplyTypeAndStatus value1, ApplyTypeAndStatus value2) {
            addCriterion("apply_status not between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("apply_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("apply_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(String value) {
            addCriterion("apply_user_id =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(String value) {
            addCriterion("apply_user_id <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(String value) {
            addCriterion("apply_user_id >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_id >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(String value) {
            addCriterion("apply_user_id <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("apply_user_id <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLike(String value) {
            addCriterion("apply_user_id like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotLike(String value) {
            addCriterion("apply_user_id not like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<String> values) {
            addCriterion("apply_user_id in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<String> values) {
            addCriterion("apply_user_id not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(String value1, String value2) {
            addCriterion("apply_user_id between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("apply_user_id not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdIsNull() {
            addCriterion("apply_org_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdIsNotNull() {
            addCriterion("apply_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdEqualTo(String value) {
            addCriterion("apply_org_id =", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdNotEqualTo(String value) {
            addCriterion("apply_org_id <>", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdGreaterThan(String value) {
            addCriterion("apply_org_id >", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_org_id >=", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdLessThan(String value) {
            addCriterion("apply_org_id <", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdLessThanOrEqualTo(String value) {
            addCriterion("apply_org_id <=", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdLike(String value) {
            addCriterion("apply_org_id like", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdNotLike(String value) {
            addCriterion("apply_org_id not like", value, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdIn(List<String> values) {
            addCriterion("apply_org_id in", values, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdNotIn(List<String> values) {
            addCriterion("apply_org_id not in", values, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdBetween(String value1, String value2) {
            addCriterion("apply_org_id between", value1, value2, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andApplyOrgIdNotBetween(String value1, String value2) {
            addCriterion("apply_org_id not between", value1, value2, "applyOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdIsNull() {
            addCriterion("examine_org_id is null");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdIsNotNull() {
            addCriterion("examine_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdEqualTo(String value) {
            addCriterion("examine_org_id =", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdNotEqualTo(String value) {
            addCriterion("examine_org_id <>", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdGreaterThan(String value) {
            addCriterion("examine_org_id >", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("examine_org_id >=", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdLessThan(String value) {
            addCriterion("examine_org_id <", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdLessThanOrEqualTo(String value) {
            addCriterion("examine_org_id <=", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdLike(String value) {
            addCriterion("examine_org_id like", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdNotLike(String value) {
            addCriterion("examine_org_id not like", value, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdIn(List<String> values) {
            addCriterion("examine_org_id in", values, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdNotIn(List<String> values) {
            addCriterion("examine_org_id not in", values, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdBetween(String value1, String value2) {
            addCriterion("examine_org_id between", value1, value2, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineOrgIdNotBetween(String value1, String value2) {
            addCriterion("examine_org_id not between", value1, value2, "examineOrgId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdIsNull() {
            addCriterion("examine_user_id is null");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdIsNotNull() {
            addCriterion("examine_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdEqualTo(String value) {
            addCriterion("examine_user_id =", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdNotEqualTo(String value) {
            addCriterion("examine_user_id <>", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdGreaterThan(String value) {
            addCriterion("examine_user_id >", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("examine_user_id >=", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdLessThan(String value) {
            addCriterion("examine_user_id <", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdLessThanOrEqualTo(String value) {
            addCriterion("examine_user_id <=", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdLike(String value) {
            addCriterion("examine_user_id like", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdNotLike(String value) {
            addCriterion("examine_user_id not like", value, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdIn(List<String> values) {
            addCriterion("examine_user_id in", values, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdNotIn(List<String> values) {
            addCriterion("examine_user_id not in", values, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdBetween(String value1, String value2) {
            addCriterion("examine_user_id between", value1, value2, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineUserIdNotBetween(String value1, String value2) {
            addCriterion("examine_user_id not between", value1, value2, "examineUserId");
            return (Criteria) this;
        }

        public Criteria andExamineContentIsNull() {
            addCriterion("examine_content is null");
            return (Criteria) this;
        }

        public Criteria andExamineContentIsNotNull() {
            addCriterion("examine_content is not null");
            return (Criteria) this;
        }

        public Criteria andExamineContentEqualTo(String value) {
            addCriterion("examine_content =", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentNotEqualTo(String value) {
            addCriterion("examine_content <>", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentGreaterThan(String value) {
            addCriterion("examine_content >", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentGreaterThanOrEqualTo(String value) {
            addCriterion("examine_content >=", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentLessThan(String value) {
            addCriterion("examine_content <", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentLessThanOrEqualTo(String value) {
            addCriterion("examine_content <=", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentLike(String value) {
            addCriterion("examine_content like", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentNotLike(String value) {
            addCriterion("examine_content not like", value, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentIn(List<String> values) {
            addCriterion("examine_content in", values, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentNotIn(List<String> values) {
            addCriterion("examine_content not in", values, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentBetween(String value1, String value2) {
            addCriterion("examine_content between", value1, value2, "examineContent");
            return (Criteria) this;
        }

        public Criteria andExamineContentNotBetween(String value1, String value2) {
            addCriterion("examine_content not between", value1, value2, "examineContent");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_apply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}