package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.ApplyTypeAndStatus;
import java.io.Serializable;
import java.util.Date;

public class SysApply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_apply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -5459288475506944130L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_title
     *
     * @mbggenerated
     */
    private String applyTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_content
     *
     * @mbggenerated
     */
    private String applyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_type
     *
     * @mbggenerated
     */
    private ApplyTypeAndStatus applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_status
     *
     * @mbggenerated
     */
    private ApplyTypeAndStatus applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_user_id
     *
     * @mbggenerated
     */
    private String applyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.apply_org_id
     *
     * @mbggenerated
     */
    private String applyOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.examine_org_id
     *
     * @mbggenerated
     */
    private String examineOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.examine_user_id
     *
     * @mbggenerated
     */
    private String examineUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.examine_content
     *
     * @mbggenerated
     */
    private String examineContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_apply.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.id
     *
     * @return the value of sys_apply.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.id
     *
     * @param id the value for sys_apply.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_title
     *
     * @return the value of sys_apply.apply_title
     *
     * @mbggenerated
     */
    public String getApplyTitle() {
        return applyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_title
     *
     * @param applyTitle the value for sys_apply.apply_title
     *
     * @mbggenerated
     */
    public void setApplyTitle(String applyTitle) {
        this.applyTitle = applyTitle == null ? null : applyTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_content
     *
     * @return the value of sys_apply.apply_content
     *
     * @mbggenerated
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_content
     *
     * @param applyContent the value for sys_apply.apply_content
     *
     * @mbggenerated
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent == null ? null : applyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_type
     *
     * @return the value of sys_apply.apply_type
     *
     * @mbggenerated
     */
    public ApplyTypeAndStatus getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_type
     *
     * @param applyType the value for sys_apply.apply_type
     *
     * @mbggenerated
     */
    public void setApplyType(ApplyTypeAndStatus applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_status
     *
     * @return the value of sys_apply.apply_status
     *
     * @mbggenerated
     */
    public ApplyTypeAndStatus getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_status
     *
     * @param applyStatus the value for sys_apply.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(ApplyTypeAndStatus applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_user_id
     *
     * @return the value of sys_apply.apply_user_id
     *
     * @mbggenerated
     */
    public String getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_user_id
     *
     * @param applyUserId the value for sys_apply.apply_user_id
     *
     * @mbggenerated
     */
    public void setApplyUserId(String applyUserId) {
        this.applyUserId = applyUserId == null ? null : applyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.apply_org_id
     *
     * @return the value of sys_apply.apply_org_id
     *
     * @mbggenerated
     */
    public String getApplyOrgId() {
        return applyOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.apply_org_id
     *
     * @param applyOrgId the value for sys_apply.apply_org_id
     *
     * @mbggenerated
     */
    public void setApplyOrgId(String applyOrgId) {
        this.applyOrgId = applyOrgId == null ? null : applyOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.examine_org_id
     *
     * @return the value of sys_apply.examine_org_id
     *
     * @mbggenerated
     */
    public String getExamineOrgId() {
        return examineOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.examine_org_id
     *
     * @param examineOrgId the value for sys_apply.examine_org_id
     *
     * @mbggenerated
     */
    public void setExamineOrgId(String examineOrgId) {
        this.examineOrgId = examineOrgId == null ? null : examineOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.examine_user_id
     *
     * @return the value of sys_apply.examine_user_id
     *
     * @mbggenerated
     */
    public String getExamineUserId() {
        return examineUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.examine_user_id
     *
     * @param examineUserId the value for sys_apply.examine_user_id
     *
     * @mbggenerated
     */
    public void setExamineUserId(String examineUserId) {
        this.examineUserId = examineUserId == null ? null : examineUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.examine_content
     *
     * @return the value of sys_apply.examine_content
     *
     * @mbggenerated
     */
    public String getExamineContent() {
        return examineContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.examine_content
     *
     * @param examineContent the value for sys_apply.examine_content
     *
     * @mbggenerated
     */
    public void setExamineContent(String examineContent) {
        this.examineContent = examineContent == null ? null : examineContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.create_time
     *
     * @return the value of sys_apply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.create_time
     *
     * @param createTime the value for sys_apply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_apply.update_time
     *
     * @return the value of sys_apply.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_apply.update_time
     *
     * @param updateTime the value for sys_apply.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}