package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.ResourceType;
import com.elextec.persist.field.enums.ShowFlag;
import java.io.Serializable;
import java.util.Date;

public class SysResources implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 4304331476807125557L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_code
     *
     * @mbggenerated
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_name
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_type
     *
     * @mbggenerated
     */
    private ResourceType resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_url
     *
     * @mbggenerated
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.res_sort
     *
     * @mbggenerated
     */
    private Integer resSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.show_flag
     *
     * @mbggenerated
     */
    private ShowFlag showFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.parent
     *
     * @mbggenerated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_code
     *
     * @return the value of sys_resources.res_code
     *
     * @mbggenerated
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_code
     *
     * @param resCode the value for sys_resources.res_code
     *
     * @mbggenerated
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_name
     *
     * @return the value of sys_resources.res_name
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_name
     *
     * @param resName the value for sys_resources.res_name
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_type
     *
     * @return the value of sys_resources.res_type
     *
     * @mbggenerated
     */
    public ResourceType getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_type
     *
     * @param resType the value for sys_resources.res_type
     *
     * @mbggenerated
     */
    public void setResType(ResourceType resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_url
     *
     * @return the value of sys_resources.res_url
     *
     * @mbggenerated
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_url
     *
     * @param resUrl the value for sys_resources.res_url
     *
     * @mbggenerated
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.res_sort
     *
     * @return the value of sys_resources.res_sort
     *
     * @mbggenerated
     */
    public Integer getResSort() {
        return resSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.res_sort
     *
     * @param resSort the value for sys_resources.res_sort
     *
     * @mbggenerated
     */
    public void setResSort(Integer resSort) {
        this.resSort = resSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.show_flag
     *
     * @return the value of sys_resources.show_flag
     *
     * @mbggenerated
     */
    public ShowFlag getShowFlag() {
        return showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.show_flag
     *
     * @param showFlag the value for sys_resources.show_flag
     *
     * @mbggenerated
     */
    public void setShowFlag(ShowFlag showFlag) {
        this.showFlag = showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.parent
     *
     * @return the value of sys_resources.parent
     *
     * @mbggenerated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.parent
     *
     * @param parent the value for sys_resources.parent
     *
     * @mbggenerated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.level
     *
     * @return the value of sys_resources.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.level
     *
     * @param level the value for sys_resources.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_user
     *
     * @return the value of sys_resources.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_user
     *
     * @param createUser the value for sys_resources.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_user
     *
     * @return the value of sys_resources.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_user
     *
     * @param updateUser the value for sys_resources.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}