package com.elextec.lease.manager.persist.model.mybatis;

import java.io.Serializable;

public class BizOrganizationWithBLOBs extends BizOrganization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_organization
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 9212143666949331516L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_business_licence_front
     *
     * @mbggenerated
     */
    private String orgBusinessLicenceFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_organization.org_business_licence_back
     *
     * @mbggenerated
     */
    private String orgBusinessLicenceBack;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_business_licence_front
     *
     * @return the value of biz_organization.org_business_licence_front
     *
     * @mbggenerated
     */
    public String getOrgBusinessLicenceFront() {
        return orgBusinessLicenceFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_business_licence_front
     *
     * @param orgBusinessLicenceFront the value for biz_organization.org_business_licence_front
     *
     * @mbggenerated
     */
    public void setOrgBusinessLicenceFront(String orgBusinessLicenceFront) {
        this.orgBusinessLicenceFront = orgBusinessLicenceFront == null ? null : orgBusinessLicenceFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_organization.org_business_licence_back
     *
     * @return the value of biz_organization.org_business_licence_back
     *
     * @mbggenerated
     */
    public String getOrgBusinessLicenceBack() {
        return orgBusinessLicenceBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_organization.org_business_licence_back
     *
     * @param orgBusinessLicenceBack the value for biz_organization.org_business_licence_back
     *
     * @mbggenerated
     */
    public void setOrgBusinessLicenceBack(String orgBusinessLicenceBack) {
        this.orgBusinessLicenceBack = orgBusinessLicenceBack == null ? null : orgBusinessLicenceBack.trim();
    }
}