package com.elextec.lease.manager.persist.model.mybatis;

import java.io.Serializable;

public class SysRefUserRoleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ref_user_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -4784927535949006970L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ref_user_role.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ref_user_role.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ref_user_role.user_id
     *
     * @return the value of sys_ref_user_role.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ref_user_role.user_id
     *
     * @param userId the value for sys_ref_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ref_user_role.role_id
     *
     * @return the value of sys_ref_user_role.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ref_user_role.role_id
     *
     * @param roleId the value for sys_ref_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}