package com.elextec.lease.manager.persist.model.mybatis;

import java.io.Serializable;

public class SysRefRoleResourcesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ref_role_resources
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -6186348679963648312L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ref_role_resources.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ref_role_resources.res_id
     *
     * @mbggenerated
     */
    private String resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ref_role_resources.role_id
     *
     * @return the value of sys_ref_role_resources.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ref_role_resources.role_id
     *
     * @param roleId the value for sys_ref_role_resources.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ref_role_resources.res_id
     *
     * @return the value of sys_ref_role_resources.res_id
     *
     * @mbggenerated
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ref_role_resources.res_id
     *
     * @param resId the value for sys_ref_role_resources.res_id
     *
     * @mbggenerated
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }
}